ttitle: Costabo1 Portfolio
remote_theme: andrewbanchich/forty-jekyll-theme
markdown: kramdown
kramdown:
  input: GFM
plugins:
  - jekyll-remote-theme

# Your info
email: cu976733@gmail.com
description: Penetration testing writeups and security research

# Social links (only ones you fill in will show)
github_username: costabo1

# Homepage tiles - pull from pages or posts
tiles_source: pages
tiles_count: 6
